### ISSUE TITLE
Tampermonkey script works on staff account for Canvas, but not student account

### ISSUE THREAD

**Issue by mun-tonsi** [simonrob/canvas-helpers#2]
If I sign in with my student account on Canvas, the Tampermonkey script doesn't trigger on the dashboard (for the smaller icons), but does work when I log in as a staff member.

The difference in the console logs between the two is that it shows "Canvas Helpers UserScript: Giving up `runWhenReady` - could not find `.ic-DashboardCard__box__header`" on my student account. 

I can see an h2 tag with that class on my staff account, but there doesn't seem to be one on my student account.

**Comment by simonrob** [comment]
Thanks – unfortunately I don't have access to a student account to see what form the dashboard takes. Could you save the page as a HTML file and post it here? (or email)

**Comment by mun-tonsi** [comment]
No worries, I'll send this over email

**Comment by simonrob** [comment]
It looks like the student page doesn't have the headers that the staff view shows. Could you update to 473ab6b86a3e7a9ffa05a9b803e9097eb7232a6f and see whether this fixes things?

**Comment by mun-tonsi** [comment]
Perfect, this works! 😃
